title: Share your world
hero_image: images/banner.png
description: Build an interactive website to share a part of your world
version: 1
listed: true
copyedit: false
last_tested: "2024-3-25"
steps:
  - 
    title: Вступ
  - 
    title: Your topic
  - 
    title: Створи і протестуй
    completion:
      - engaged
  - 
    title: Пошир свій проєкт
    completion:
      - internal
  - 
    title: Рефлексія
    completion:
      - external
  - 
    title: Вдосконалення твого проєкту
  - 
    title: Що далі?
