title: Share your world
hero_image: images/banner.png
description: Build an interactive website to share a part of your world
version: 1
listed: true
copyedit: false
last_tested: "2024-3-25"
steps:
  - 
    title: Introduction
  - 
    title: Ton sujet
  - 
    title: Créer et tester
    completion:
      - engaged
  - 
    title: Partager
    completion:
      - internal
  - 
    title: Réflexion
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
